### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by keenwon** [aTool-org/GitHub-Helper.Chrome#3]
chrome: 55.0.2855.0 canary (64-bit)

![image](https://cloud.githubusercontent.com/assets/5516478/18411962/517f07da-77b6-11e6-8821-78cb769abc19.png)

![image](https://cloud.githubusercontent.com/assets/5516478/18411964/61017fee-77b6-11e6-85aa-bec2e0bf2bad.png)

**Comment by hustcc** [comment]
I will update this afternoon…thanke for youfeedback.

**Comment by hustcc** [comment]
publish v1.2.1, you can update it.
