### ISSUE TITLE
Enterprise support

### ISSUE THREAD

**Issue by gaborbernat** [aTool-org/GitHub-Helper.Chrome#4]
Can you add an option where to add further sites to enable on (so be available on Github Enterprise Installations?) ? Similar to how github.expandinizr has it?

**Comment by hustcc** [comment]
Sorry, I do not know what you say.

What are further sites ?

What is github.expandinizr ?

**Comment by gaborbernat** [comment]
See [here github.expandinizr](https://github.com/thecodejunkie/github.expandinizr).

[Github Enterprise](https://enterprise.github.com/home) allows you to have a private copy of Github, which you can host under your own URL, e.g. magic.com/123. So in order to use the plugin on that copy you need to enable it on that site too, as github.expandinizr gives you the option to do so.

**Comment by hustcc** [comment]
OK, I know, then need one place to config which domain to trigger the plugin.

**Comment by gaborbernat** [comment]
@hustcc any progress on this?

**Comment by hustcc** [comment]
This will update the plugin to monitor all the website url(*), maybe not a very nice way.

I think you can fork the code, then update the `manifest.json` with your github domain, then release into chrome-extention store or realese in you company.
